# Generated by Django 3.2.6 on 2021-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_chat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
