# Generated by Django 3.2.6 on 2021-08-31 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_chat_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship1', to='feed.friendlist')),
                ('friendship2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship2', to='feed.friendlist')),
            ],
            options={
                'unique_together': {('friendship1', 'friendship2')},
            },
        ),
    ]
