# Generated by Django 3.2.6 on 2021-08-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='date',
        ),
    ]
