# Generated by Django 4.0.3 on 2022-03-27 21:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('giftCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftCard', to='feed.giftcards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logHistory', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None), blank=True, size=None)),
                ('giftCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftCardName2', to='feed.usergiftcard')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productOrdered', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateTimeField()),
                ('orderNumber', models.CharField(max_length=200)),
                ('giftCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftCardName', to='feed.usergiftcard')),
            ],
        ),
    ]
