# Generated by Django 4.0.3 on 2022-03-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiftCards',
            new_name='GiftCard',
        ),
    ]
