# Generated by Django 4.0.3 on 2022-03-28 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_rename_giftcards_giftcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergiftcard',
            unique_together={('user', 'giftCard')},
        ),
    ]
