# Generated by Django 4.0.3 on 2022-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
