# Generated by Django 3.2.3 on 2021-05-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('student', 'teacher', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('teacher', 'course')},
        ),
    ]
