# Generated by Django 3.1 on 2021-07-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group5', to='Users.groups'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('teacher', 'course', 'group')},
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
