# Generated by Django 3.1 on 2021-07-22 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210722_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course0', to='Users.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher0', to='Users.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'course')},
            },
        ),
    ]
