# Generated by Django 3.1 on 2021-07-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_teachercourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherCourses',
            new_name='TeacherCourse',
        ),
    ]
