POST http://localhost:3001/post/api
Content-Type: application/json

{
    "id": 0,
    "error": null,
    "result": [
        {
            "profiles": [
                {
                    "name": "Gucci",
                    "profile_added": "2021-11-24T12:12:55.405Z",
                    "id": "44596321012",
                    "profile_type": "facebook_page"
                },
                {
                    "name": "Gucci Official",
                    "profile_added": "2021-11-24T12:12:56.104Z",
                    "id": "gucci",
                    "profile_type": "instagram_profile"
                },
                {
                    "name": "gucci",
                    "profile_added": "2021-11-24T12:12:57.817Z",
                    "id": "16913418",
                    "profile_type": "twitter_profile"
                }
            ],
            "brandname": "Gucci"
        },
        {
            "profiles": [
                {
                    "name": "H&M",
                    "profile_added": "2022-02-09T12:39:38.340Z",
                    "id": "21415640912",
                    "profile_type": "facebook_page"
                },
                {
                    "name": "H&M",
                    "profile_added": "2022-02-09T12:39:39.222Z",
                    "id": "hm",
                    "profile_type": "instagram_profile"
                },
                {
                    "name": "hm",
                    "profile_added": "2022-02-09T12:39:40.516Z",
                    "id": "14399483",
                    "profile_type": "twitter_profile"
                }
            ],
            "brandname": "HM"
        },
        {
            "profiles": [
                {
                    "name": "adidas",
                    "profile_added": "2022-02-09T12:39:47.938Z",
                    "id": "182162001806727",
                    "profile_type": "facebook_page"
                },
                {
                    "name": "adidas",
                    "profile_added": "2022-02-09T12:39:48.818Z",
                    "id": "adidas",
                    "profile_type": "instagram_profile"
                },
                {
                    "name": "adidas",
                    "profile_added": "2022-02-09T12:39:51.726Z",
                    "id": "300114634",
                    "profile_type": "twitter_profile"
                }
            ],
            "brandname": "Adidas"
        },
        {
            "profiles": [
                {
                    "name": "Nike",
                    "profile_added": "2022-02-09T12:40:26.184Z",
                    "id": "15087023444",
                    "profile_type": "facebook_page"
                },
                {
                    "name": "Nike",
                    "profile_added": "2022-02-09T12:40:26.791Z",
                    "id": "nike",
                    "profile_type": "instagram_profile"
                },
                {
                    "name": "Nike",
                    "profile_added": "2022-02-09T12: 40: 27.898Z",
                    "id": "415859364",
                    "profile_type": "twitter_profile"
                }
            ],
            "brandname": "Nike"
        }
    ]
}
