# Generated by Django 3.1 on 2022-02-27 23:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('text', models.TextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('friendship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to='feed.friendlist')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship1', to='feed.friendlist')),
                ('friendship2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship2', to='feed.friendlist')),
            ],
            options={
                'unique_together': {('friendship1', 'friendship2')},
            },
        ),
    ]
